### ISSUE TITLE
Could you please offer the train/val split of the EDS_dataset?

### ISSUE THREAD

**Issue by ghost** [DIG-Beihang/PSN#2]
Could you please offer the train/val split of the EDS_dataset?

**Comment by Victory8858** [comment]
Can you reproduce the result reported in this paper? I can't, even I use the trainval set for train and trainval set for test, you can think what is the result of only use train set to train and val set to test, I think it will be much lower, I ask the question to the author, but no reply.

**Comment by omid-reza** [comment]
I have not got any response also!
